apiVersion: appconnect.ibm.com/v1beta1
kind: DesignerAuthoring
metadata:
  name: ace-designer-ai
  namespace: tools
spec:
  couchdb:
    storage:
      size: 10Gi
      type: persistent-claim
      class: ibmc-block-gold
  designerFlowsOperationMode: local
  designerMappingAssist:
    enabled: true
    incrementalLearning:
      schedule: Every 15 days
      useIncrementalLearning: true
      storage:
        type: persistent-claim
        class: ibmc-file-gold-gid
  license:
    accept: true
    license: L-APEH-CCHL5W
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  switchServer:
    name: ace-switch-server
  useCommonServices: true
  version: 12.0-lts