apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: openshift-operators
spec:
  channel: v2.0
  name: ibm-mq
  source: ibmmq-operator-catalogsource
  sourceNamespace: openshift-marketplace