global: {}

ibm-mq-operator:
  subscriptions:
    ibmmq:
      name: ibm-mq
      subscription:
        channel: 
        installPlanApproval: Automatic
        name: ibm-mq
        source: ibm-operator-catalog
        sourceNamespace: openshift-marketplace